trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  buildConfiguration: 'Release'
  azureArtifactsFeed: 'Personal/personal-feed'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true

  - script: dotnet build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'

  - task: NuGetCommand@2
    displayName: 'NuGet Push - $(azureArtifactsFeed)'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      publishVstsFeed: '$(azureArtifactsFeed)'
      allowPackageConflicts: true
